import type { Rule } from '@unocss/core';

import { bgColors, opacity, textColors } from './color';
import { insets, positions } from './position';
import { fontSmoothings, fonts } from './typography';

export const rules: Rule[] = [
  // cssVariables,
  // cssProperty,
  // paddings,
  // margins,
  // displays,
  opacity,
  bgColors,
  // svgUtilities,
  // borders,
  // contents,
  fonts,
  // tabSizes,
  // textIndents,
  // textOverflows,
  // textDecorations,
  // textStrokes,
  // textShadows,
  // textTransforms,
  // textAligns,
  textColors,
  // fontStyles,
  fontSmoothings,
  // boxShadows,
  // rings,
  // flex,
  // grids,
  // gaps,
  positions,
  // sizes,
  // aspectRatio,
  // cursors,
  // appearances,
  // pointerEvents,
  // resizes,
  // verticalAligns,
  // userSelects,
  // whitespaces,
  // breaks,
  // overflows,
  // outline,
  // appearance,
  // orders,
  // justifies,
  // alignments,
  // placements,
  insets,
  // floats,
  // zIndexes,
  // boxSizing,
  // transitions,
  // transforms,
  // willChange,

  // should be the last
  // questionMark,
].flat(1);
