import type { Rule } from '@unocss/core';

import { borders } from './border';
import { bgColors, opacity, textColors } from './color';
import { filters } from './filter';
import { insets, positions, zIndexes } from './position';
import { aspectRatio, sizes } from './size';
import { transitions } from './transition';
import { fontSmoothings, fonts } from './typography';

export const rules: Rule[] = [
  // miniCssVariables,
  // cssVariables,
  // cssProperty,
  // container,
  // screenReadersAccess,
  // pointerEvents,
  // appearances,
  positions,
  insets,
  // lineClamps,
  // isolations,
  zIndexes,
  // orders,
  // grids,
  // floats,
  // margins,
  // boxSizing,
  // displays,
  aspectRatio,
  sizes,
  // flex,
  // tables,
  // transforms,
  // animations,
  // cursors,
  // touchActions,
  // userSelects,
  // resizes,
  // scrolls,
  // listStyle,
  // appearance,
  // columns,
  // placements,
  // alignments,
  // justifies,
  // gaps,
  // spaces,
  // divides,
  // overflows,
  // overscrolls,
  // scrollBehaviors,
  // textOverflows,
  // whitespaces,
  // wordBreaks,
  borders,
  bgColors,
  // backgroundStyles,
  // svgUtilities,
  // objectPositions,
  // paddings,
  // textAligns,
  // textIndents,
  // verticalAligns,
  fonts,
  // miniTextTransforms,
  // textTransforms,
  // fontStyles,
  // fontVariantNumeric,
  textColors,
  // textDecorations,
  fontSmoothings,
  // TODO placeholders,
  // tabSizes,
  // textStrokes,
  // textShadows,
  // hyphens,
  // writingModes,
  // writingOrientations,
  // carets,
  // accents,
  opacity,
  // backgroundBlendModes,
  // mixBlendModes,
  // boxShadows,
  // outline,
  // rings,
  // imageRenderings,
  filters,
  transitions,
  // willChange,
  // contents,
  // placeholders,

  // should be the last
  // questionMark,
].flat(1);
