name: Publish to NPM registry

on:
  push:
    branches:
      - 'build/poc'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Print version
        run: echo $GITHUB_ENV
  