name: Publish to NPM registry

on:
  push:
    branches:
      - 'build/poc'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        run: echo "${GITHUB_REF#refs/*/}"
  